// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID           int64
	UserID       int64
	Company      string
	Title        string
	Link         string
	Status       string
	Salary       string
	Notes        string
	FollowUpDate pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
