// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (user_id, company, title, link, status, salary, notes, follow_up_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, company, title, link, status, salary, notes, follow_up_date, created_at, updated_at
`

type CreateJobParams struct {
	UserID       int64
	Company      string
	Title        string
	Link         string
	Status       string
	Salary       string
	Notes        string
	FollowUpDate pgtype.Date
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.UserID,
		arg.Company,
		arg.Title,
		arg.Link,
		arg.Status,
		arg.Salary,
		arg.Notes,
		arg.FollowUpDate,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Company,
		&i.Title,
		&i.Link,
		&i.Status,
		&i.Salary,
		&i.Notes,
		&i.FollowUpDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1 AND user_id = $2
`

type DeleteJobParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.Exec(ctx, deleteJob, arg.ID, arg.UserID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, user_id, company, title, link, status, salary, notes, follow_up_date, created_at, updated_at
FROM jobs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context, userID int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Company,
			&i.Title,
			&i.Link,
			&i.Status,
			&i.Salary,
			&i.Notes,
			&i.FollowUpDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET company = $2,
    title = $3,
    link = $4,
    status = $5,
    salary = $6,
    notes = $7,
    follow_up_date = $8,
    updated_at = now()
WHERE id = $1 AND user_id = $9
RETURNING id, user_id, company, title, link, status, salary, notes, follow_up_date, created_at, updated_at
`

type UpdateJobParams struct {
	ID           int64
	Company      string
	Title        string
	Link         string
	Status       string
	Salary       string
	Notes        string
	FollowUpDate pgtype.Date
	UserID       int64
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Company,
		arg.Title,
		arg.Link,
		arg.Status,
		arg.Salary,
		arg.Notes,
		arg.FollowUpDate,
		arg.UserID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Company,
		&i.Title,
		&i.Link,
		&i.Status,
		&i.Salary,
		&i.Notes,
		&i.FollowUpDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
